version: "{build}"
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    dotnet tool install -g housework

    housework setbuildnumber %FileVersion% -s build.ini

    housework author src/NetBox/NetBox.csproj -s build.ini

    dotnet restore src/netbox.sln
build:
  project: src/netbox.sln
  verbosity: minimal
test_script:
- cmd: dotnet test src\NetBox.Tests\NetBox.Tests.csproj
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: hQlxhZb6uDjtZz4V+DZyAqjxnGjXqEokO/tckU14RDUP/AxTkFnX869pNsXCv+Ab
  on:
    branch: master