version: "{build}"
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    dotnet tool install dotnet-housework -g

    dotnet housework setbuildnumber %FileVersion% build.ini

    dotnet housework author src/NetBox/NetBox.csproj build.ini

    dotnet restore src/netbox.sln
build:
  project: src/netbox.sln
  verbosity: minimal
test_script:
- cmd: dotnet test src\NetBox.Tests\NetBox.Tests.csproj
artifacts:
- path: src/**/*.nupkg
deploy: off