version: "{build}"
image: Visual Studio 2017
configuration: Release
before_build:
- ps: >-
    dotnet restore src/netbox.sln

    cd src/netbox

    dotnet housework author .\NetBox.csproj  ../../build.ini

    cd ../..
build:
  project: src/netbox.sln
  verbosity: minimal
test_script:
- cmd: dotnet test src\NetBox.Tests\NetBox.Tests.csproj
artifacts:
- path: src/**/*.nupkg
deploy: off