trigger:
  batch: true
  branches:
    include:
      - master
      - cli
  paths:
    exclude:
      - README.md
      - doc/**/*

pr:
  branches:
    include:
      - v6
      - master
  paths:
    exclude:
      - README.md

variables:
  - name: vmImage
    value: 'ubuntu-16.04'  # see https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts

stages:
- stage: Build
  jobs:
  - job: Core
    pool:
      vmImage: $(vmImage)

    steps:

    - task: PowerShell@2
      displayName: 'manual authoring'
      inputs:
        filePath: 'build.ps1'
        pwsh: true

    - task: DotNetCoreCLI@2
      displayName: 'build all'
      inputs:
        projects: src/netbox.sln
        arguments: '-c release'

    - task: DotNetCoreCLI@2
      displayName: 'unit tests'
      inputs:
        command: test
        projects: ./src/netbox.sln

    - task: CopyFiles@2
      displayName: 'copy generated nugets'
      inputs:
        SourceFolder: src
        Contents: '**/*.nupkg'
        TargetFolder: ' $(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'publish nugets'
      inputs:
        ArtifactName: nuget

- stage: Deploy
  condition: "and( eq(variables['Build.SourceBranch'], 'refs/heads/master'), succeeded('Build') )"
  jobs:
  - deployment: NugetOrg
    pool:
      vmImage: $(vmImage)
    environment: live
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'nuget'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: NuGetCommand@2
            displayName: nuget.org
            inputs:
              command: push
              packagesToPush: '$(System.ArtifactsDirectory)/nuget/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'nuget.org (aloneguid)'
