trigger:
  branches:
    include:
      - master
      - cli
  paths:
    exclude:
      - README.md
      - doc/**/*

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md

variables:
  - name: vmImage
    value: 'ubuntu-latest'
  - name: v
    value: '2.5.0'
  - name: av
    value: '2.0.0'
  - name: pv
    value: '2.5.1'

stages:
- stage: Build
  jobs:
  - job: Core
    displayName: 'lib and CLI'
    pool:
      vmImage: $(vmImage)

    steps:

    - script: echo "##vso[build.updatebuildnumber]$(pv)"

    - task: DotNetCoreCLI@2
      displayName: 'unit tests'
      inputs:
        command: test
        projects: ./src/netbox.sln
        arguments: '-c release /p:Version=$(pv) /p:FileVersion=$(v) /p:AssemblyVersion=$(av)'

    - task: DotNetCoreCLI@2
      displayName: 'build all'
      inputs:
        projects: src/netbox.sln
        arguments: '-c release /p:Version=$(pv) /p:FileVersion=$(v) /p:AssemblyVersion=$(av)'


    - task: CopyFiles@2
      displayName: 'copy generated nugets'
      inputs:
        SourceFolder: src
        Contents: '**/*.nupkg'
        TargetFolder: ' $(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'publish nugets'
      inputs:
        ArtifactName: nuget

- stage: Deploy
  condition: "and( eq(variables['Build.SourceBranch'], 'refs/heads/master'), succeeded('Build') )"
  jobs:
  - deployment: NugetOrg
    pool:
      vmImage: $(vmImage)
    environment: live
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'nuget'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: NuGetCommand@2
            displayName: nuget.org
            inputs:
              command: push
              packagesToPush: '$(System.ArtifactsDirectory)/nuget/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'nuget.org (aloneguid)'
