name: Full Cycle

env:
  v: '4.1.1'
  av: '4.0.0'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  justdoit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: dotnet restore src/netbox.sln
    - name: Test
      run: dotnet test src/netbox.sln --no-restore --verbosity normal
    - name: Pack to single file
      run: python3 pack.py
    - name: copy to project
      run: cp NetBox.cs src/singlefile/
    - name: Validate single .cs compiles
      run: dotnet build src/singlefile/
    - name: Archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./NetBox.cs
    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
         tag_name: ${{ env.v }}
         name: ${{ env.v }}
         files: NetBox.cs
