name: .NET Core

env:
  v: '2.5.0'
  av: '2.0.0'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/netbox.sln
    - name: Build
      run: dotnet build src/netbox.sln --configuration Release --no-restore /p:Version=${{ env.v }} /p:FileVersion=${{ env.v }} /p:AssemblyVersion=${{ env.av }}
    - name: Test
      run: dotnet test src/netbox.sln --no-restore --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: packages
        path: src/NetBox/bin/Release/*.nupkg
#     - name: Configure GitHub Packages
#       run: dotnet nuget add source https://nuget.pkg.github.com/aloneguid/index.json -n github -u aloneguid -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
#     - name: Publish
#       run: dotnet nuget push "src/NetBox/bin/Release/*.nupkg" --source "github" --skip-duplicate
#     - name: Publish to GitHub Packages
#       run: dotnet nuget push src/NetBox/bin/Release/*.nupkg --skip-duplicate --api-key ${{ github.token }} --source https://nuget.pkg.github.com/aloneguid/index.json
    - name: Publish to GitHub Package Registry
      run: |
        nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/aloneguid/index.json" -UserName aloneguid -Password ${{ secrets.GITHUB_TOKEN }}
        nuget push src/NetBox/bin/Release/*.nupkg -Source "GitHub" -SkipDuplicate
      
  publishNuGetOrg:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Do It!
        run: nuget source add
