name: Brave Release!

env:
  v: '2.5.2'
  av: '2.0.0'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/netbox.sln
    - name: Build
      run: dotnet build src/netbox.sln --configuration Release --no-restore /p:Version=${{ env.v }} /p:FileVersion=${{ env.v }} /p:AssemblyVersion=${{ env.av }}
    - name: Test
      run: dotnet test src/netbox.sln --no-restore --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: packages
        path: src/NetBox/bin/Release/*.nupkg
      
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.6
        with:
          name: packages
      - name: Do It!
        run: dotnet nuget push *.nupkg --api-key ${{ secrets. NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
