name: Validation

env:
  v: '3.0.0'
  av: '3.0.0'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
    - name: Install dependencies
      run: dotnet restore src/netbox.sln
    - name: Test
      run: dotnet test src/netbox.sln --no-restore --verbosity normal
    - name: Pack to single file
      run: ./pack.sh
    - name: Validate single .cs compiles
      run: csc NetBox.cs
    - name: Archive as artifact
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: ./NetBox.cs
